#!/bin/bash
if [ -z "$1" ]
    then
	echo "Please provide file name (app-name/version/version.zip)"
	exit
fi
filename=`basename $1`
directory=`pwd`
cd /tmp
wget https://projector-app-store.herokuapp.com/download/$1 -O /tmp/download.zip
unzip -o /tmp/download.zip
rm /tmp/download.zip
cd "$directory/react-ui/src/apps"
unzip -o /tmp/$filename
src=`unzip -Z1 /tmp/$filename | head -1`
dst=`echo $1 | grep -o [^/]*`
mv $src $dst
rm /tmp/$filename
